[package]
name = "pallet-encointer-bazaar-rpc"
version = "1.0.0"
authors = ["encointer.org <alain@encointer.org>"]
edition = "2021"

[dependencies]
jsonrpsee = { version = "0.12.0", features = ["server", "macros"] }
log = "0.4.14"
parking_lot = "0.12.0"
tokio = { version = "1.17.0", features = ["macros"] }

# local deps
encointer-primitives = { path = "../../primitives" }
encointer-bazaar-rpc-runtime-api = { package = "pallet-encointer-bazaar-rpc-runtime-api", path = "runtime-api" }

# substrate deps
sc-rpc = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", branch = "master" }
sc-rpc-api = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate.git", branch = "master" }
sp-api = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", branch = "master" }
sp-blockchain = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", branch = "master" }
sp-runtime = { version = "6.0.0", git = "https://github.com/paritytech/substrate.git", branch = "master" }
