[package]
name = "pallet-encointer-sybil-proof-issuer"
version = "0.3.9"
authors = ["encointer.org <alain@encointer.org>"]
edition = "2018"

[dependencies.encointer-primitives]
default-features = false
package = "encointer-primitives"
path = "../../primitives"

[dependencies.encointer-balances]
default-features = false
path = "../../balances"
package = "pallet-encointer-balances"

[dependencies.encointer-ceremonies]
default-features = false
path = "../../ceremonies"
package = "pallet-encointer-ceremonies"

[dependencies.encointer-communities]
default-features = false
path = "../../communities"
package = "pallet-encointer-communities"

[dependencies.encointer-scheduler]
default-features = false
path = "../../scheduler"
package = "pallet-encointer-scheduler"

[dependencies.codec]
default-features = false
package = "parity-scale-codec"
features = ["derive"]
version = "1.3.6"

[dependencies.rstd]
default-features = false
package = "sp-std"
git = "https://github.com/paritytech/substrate.git"
rev = "38f723bf"

[dependencies.frame-system]
default-features = false
package = "frame-system"
git = "https://github.com/paritytech/substrate.git"
rev = "38f723bf"

[dependencies.frame-support]
default-features = false
package = "frame-support"
git = "https://github.com/paritytech/substrate.git"
rev = "38f723bf"

[dependencies.polkadot-parachain]
default-features = false
git = "https://github.com/paritytech/polkadot"
rev = "4a94b71ed7abdba231de8a03a7a22975cab6a079" # commit from the same day as the substrate commit we use

[dependencies.sp-core]
default-features = false
package = "sp-core"
git = "https://github.com/paritytech/substrate.git"
rev = "38f723bf"

[dependencies.sp-runtime]
default-features = false
package = "sp-runtime"
git = "https://github.com/paritytech/substrate.git"
rev = "38f723bf"

[dependencies.timestamp]
default-features = false
package = "pallet-timestamp"
git = "https://github.com/paritytech/substrate.git"
rev = "38f723bf"

[dependencies.xcm]
default-features = false
git = "https://github.com/paritytech/polkadot"
rev = "4a94b71ed7abdba231de8a03a7a22975cab6a079" # commit from the same day as the substrate commit we use

[dependencies.sp-io]
default-features = false
package = "sp-io"
git = "https://github.com/paritytech/substrate.git"
rev = "38f723bf"

[dev-dependencies.sp-keyring]
package = "sp-keyring"
git = "https://github.com/paritytech/substrate.git"
rev = "38f723bf"

[dev-dependencies.xcm-builder]
git = "https://github.com/paritytech/polkadot.git"
rev = "4a94b71ed7abdba231de8a03a7a22975cab6a079" # commit from the same day as the substrate commit we use

[dev-dependencies.xcm-executor]
git = "https://github.com/paritytech/polkadot.git"
rev = "4a94b71ed7abdba231de8a03a7a22975cab6a079" # commit from the same day as the substrate commit we use

[dev-dependencies.test-utils]
path = "../../test-utils"

[features]
default = ["std"]
std = [
    "codec/std",
    "rstd/std",
    "frame-system/std",
    "frame-support/std",
    "xcm/std",
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "timestamp/std",
    "encointer-ceremonies/std",
    "encointer-communities/std",
    "encointer-scheduler/std",
    "encointer-balances/std",
    "encointer-primitives/std",
    "polkadot-parachain/std"
]